name: basic-workflow
on:
  workflow_dispatch:
  inputs:
    name:
      description: 'Name to greet'
      required: true
      default: 'World'
      type: string
    city_option:
      description: 'City to include in the greeting'
      required: true
      default: 'New York'
      type: choice
      options:
        - 'New York'
        - 'Los Angeles'
        - 'Chicago'
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet User
        run: echo "Hello, ${{ github.event.inputs.name }} from ${{ github.event.inputs.city_option }}!"